<!DOCTYPE html>
<!-- DO NOT EDIT THIS FILE -->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE EXECUTED !!! -->
<html>
<head>
    <title>Thank You - Well Received!</title>
</head>
<body>
    <h1>It is EMPTY here. We will write PHP in Week 3!</h1>
    <h2>Hang in there!</h2>
    <pre>
    <?php
        var_dump($_GET);
    ?>
    </pre>
</body>
</html>