<?php
// Do NOT edit this file!!!

require_once 'functions.php';
?>

<html>
<body>
   <table>
   <tr>
      <th>
         luckStringToDict( 'NORMALx2, GOODx2, BADx2, NORMALx3, BAD' )<br/>
      </th>
      <th>
      luckStringToDict( 'NORMALx2, GOOD' )<br/>
      </th>
   </tr>
   <tr>
      <td>
         <?php
         var_dump( luckStringToDict( 'NORMALx2, GOODx2, BADx2, NORMALx3, BAD' ) );
         ?>
      </td>
      <td>
         <?php
         var_dump( luckStringToDict( 'NORMALx2, GOOD' ) );
         ?>
      </td>
   </tr>
   </table>
   
</body>
</html>
