<?php
// DO NOT EDIT THIS FILE!

$mediaFormat = [
	'hardcopies' => 'Hardcopies (e.g. Book)',
	'dvd' => 'DVD',
	'stream' => 'Streaming (e.g. Spotify, YouTube)'
];	
$errors = [];

if ( !isset($_GET['btnSend']) ) {
	$errors[] = 'Please fill in all fields and and click "Send the form!" to submit the <a href="index.html">form</a>.';
	
} else {
	
	$id = trim($_GET['id']);	
	if ( strlen($id) == 0) {
		$errors[] = 'Title / Name cannot be empty.';
	}
	
	if ( isset($_GET['lang']) ) {		
		switch ($_GET['lang']) {
			case 'EN':
				$lang = 'english';
				break;
			case 'CH':
				$lang = 'chinese';
				break;
			case 'OTH':
				$lang = 'a foreign language';
				break;

		}
	} else {
		$errors[] = 'Please select a language.';
	}

	if ( isset($_GET['medium']) ) {
		$mediumArr = $_GET['medium'];
	} else {
		$errors[] = 'Please select one or more media format.';
	}
	
	$rating = $_GET['rating'];
	if ($rating == 'g') {
		$suitablity = 'all ages';		
	} elseif  ($rating == 'pg') {
		$suitablity = '12 years old and above';
	} else {
		$suitablity = '18 years old and above';
	}

}
?>
<html>
<body>

	<?php
		if ( count($errors) == 0) {
	?>
			<h1><?=$id?></h1>
			<p>
				It is in <?=$lang?> and suitable for <?=$suitablity?>.  
				It is available in the following format(s):
			</p>
			
			<ul>
			<?php
				foreach ($mediumArr as $medium) {
					$format = $mediaFormat[$medium];
					echo "
						<li>$format</li>
					";
				}
			?>
			</ul>
	<?php
		} else {
			echo '
				<ol>
			';
			foreach ($errors as $e) {
				echo "
					<li>$e</li>
				";
			}
			echo '
				</ol>
				Back to the <a href="index.html">form</a>.
			';
			
		}
	?>

</body>
</html>
